version: '2'

services:
  icecast:
    #image: vitiman/alpine-icecast:latest
    build: ./icecast
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - music_stack
    restart: always

  # Add your host volumen in path/to/... or add your own volume below
  mpd:
    build: ./mpd
    #image: bse666/rpi-mopidy
    ports:
      - "6600:6600"
      - "6680:6680"
    depends_on:
      - icecast
    networks:
      - music_stack
    volumes:
      - /home/pirate/music:/var/lib/mpd/music
#      - /path/to/mpd_playlists:/var/lib/mpd/playlists
#      - /path/to/mpd_database:/var/lib/mpd/database
    restart: always

  #sima:
  #  #image: vitiman/alpine-sima:latest
  #  build: ./sima
  #  depends_on:
  #    - mpd
  #  networks:
  #    - music_stack
    #restart: always

  ympd:
    #image: vitiman/alpine-ympd:latest
    build: ./ympd
    ports:
      - "8080:8080"
    depends_on:
      - mpd
    networks:
      - music_stack
    restart: always

networks:
  music_stack:
    driver: bridge

# If you use your own volumes instead host volumes, uncomment this section
# volumes:
#   mpd_music:
#     external: true
#   mpd_playlists:
#     external: true
#   mpd_database:
#     external: true


